# Generated by Django 4.2.3 on 2024-05-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qr_app", "0007_alter_qr_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qr",
            name="created_at",
            field=models.DateTimeField(default="2024-05-23T15:01:41.733818"),
        ),
    ]
